/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package necflis;

import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Edman
 */
public class Clientes extends javax.swing.JInternalFrame {

    /**
     * Creates new form Clientes
     */
    
    public Clientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktop = new javax.swing.JDesktopPane();
        Nue_Cliente = new javax.swing.JButton();
        Sele_Cliente = new javax.swing.JButton();
        ListClientes = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Clientes");

        jDesktop.setBackground(new java.awt.Color(255, 255, 255));

        Nue_Cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/necflis/nuevo.png"))); // NOI18N
        Nue_Cliente.setText("Crear Nuevo Cliente");
        Nue_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nue_ClienteActionPerformed(evt);
            }
        });

        Sele_Cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/necflis/seleccionar.jpg"))); // NOI18N
        Sele_Cliente.setText("Seleccionar Cliente");
        Sele_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sele_ClienteActionPerformed(evt);
            }
        });

        ListClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/necflis/listado.png"))); // NOI18N
        ListClientes.setText("Ver Listado de Clientes");
        ListClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListClientesActionPerformed(evt);
            }
        });

        jDesktop.setLayer(Nue_Cliente, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktop.setLayer(Sele_Cliente, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktop.setLayer(ListClientes, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopLayout = new javax.swing.GroupLayout(jDesktop);
        jDesktop.setLayout(jDesktopLayout);
        jDesktopLayout.setHorizontalGroup(
            jDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopLayout.createSequentialGroup()
                .addGap(266, 266, 266)
                .addGroup(jDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ListClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nue_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Sele_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(284, Short.MAX_VALUE))
        );
        jDesktopLayout.setVerticalGroup(
            jDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopLayout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(ListClientes)
                .addGap(47, 47, 47)
                .addComponent(Nue_Cliente)
                .addGap(49, 49, 49)
                .addComponent(Sele_Cliente)
                .addContainerGap(130, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktop)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Sele_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sele_ClienteActionPerformed
        necflis.SeleccionarCliente sc= new necflis.SeleccionarCliente();
        jDesktop.add(sc);
        sc.show();
    }//GEN-LAST:event_Sele_ClienteActionPerformed

    private void Nue_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nue_ClienteActionPerformed
        necflis.NuevoCliente n = new necflis.NuevoCliente();
        jDesktop.add(n);
        n.show();
    }//GEN-LAST:event_Nue_ClienteActionPerformed

    private void ListClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListClientesActionPerformed
        necflis.ListadoClientes l = new necflis.ListadoClientes();
        jDesktop.add(l);
        l.show();
    }//GEN-LAST:event_ListClientesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ListClientes;
    private javax.swing.JButton Nue_Cliente;
    private javax.swing.JButton Sele_Cliente;
    private javax.swing.JDesktopPane jDesktop;
    // End of variables declaration//GEN-END:variables
}
