/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package necflis;

import java.io.FileWriter;
import javax.swing.JOptionPane;

/**
 *
 * @author Edman
 */
public class NuevaPelicula extends javax.swing.JInternalFrame {

    /**
     * Creates new form NuevaPelicula
     */
    public NuevaPelicula() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        btnAñadir = new javax.swing.JButton();
        JT_Pelicula = new javax.swing.JTextField();
        JT_Tipo = new javax.swing.JTextField();
        jLabelSuel1 = new javax.swing.JLabel();
        JT_Genero = new javax.swing.JTextField();
        jLabelSuel2 = new javax.swing.JLabel();
        JT_Sinopsis = new javax.swing.JTextField();
        jLabelPuest = new javax.swing.JLabel();
        jLabelSuel = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Agregar Película");

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));

        btnAñadir.setText("Añadir");
        btnAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirActionPerformed(evt);
            }
        });

        JT_Pelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JT_PeliculaActionPerformed(evt);
            }
        });
        JT_Pelicula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JT_PeliculaKeyPressed(evt);
            }
        });

        jLabelSuel1.setText("Género:");

        jLabelSuel2.setText("Sinopsis:");

        jLabelPuest.setText("Ingrese Nombre de Película:");

        jLabelSuel.setText("Tipo (Película o Serie):");

        jDesktopPane1.setLayer(btnAñadir, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(JT_Pelicula, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(JT_Tipo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabelSuel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(JT_Genero, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabelSuel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(JT_Sinopsis, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabelPuest, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabelSuel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAñadir)
                        .addGap(229, 229, 229))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(jLabelSuel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JT_Sinopsis, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(jLabelSuel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JT_Genero, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(jLabelSuel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JT_Tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(jLabelPuest)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                                .addComponent(JT_Pelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(167, 167, 167))))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JT_Pelicula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPuest))
                .addGap(31, 31, 31)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JT_Tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSuel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JT_Genero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSuel1))
                .addGap(28, 28, 28)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JT_Sinopsis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSuel2))
                .addGap(50, 50, 50)
                .addComponent(btnAñadir)
                .addGap(70, 70, 70))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirActionPerformed
        String pelicula = JT_Pelicula.getText();
        String tipo  = JT_Tipo.getText();
        String genero = JT_Genero.getText();
        String sinopsis = JT_Sinopsis.getText();

        try{
            FileWriter Writer = new FileWriter("peliculas.txt", true);
            Writer.write(""+pelicula+"-"+tipo+"-"+genero+"-"+sinopsis+"");
            Writer.write(System.getProperty("line.separator"));
            Writer.close();
            JOptionPane.showMessageDialog(null,"Nueva Película Agregada");
            setVisible(false);
            new NuevaPelicula().setVisible(true);
        }

        catch (Exception e){
            JOptionPane.showMessageDialog(null,"Error");
        }
        try{
            FileWriter Writer2 = new FileWriter("peliculasdisponibles.txt", true);
            Writer2.write(""+pelicula);
            Writer2.write(System.getProperty("line.separator"));
            Writer2.close();
            //JOptionPane.showMessageDialog(null,"Nueva Película Agregada");
            setVisible(false);
            new NuevaPelicula().setVisible(true);
        }

        catch (Exception e){
            JOptionPane.showMessageDialog(null,"Error");
        }
            
        
    }//GEN-LAST:event_btnAñadirActionPerformed

    private void JT_PeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JT_PeliculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JT_PeliculaActionPerformed

    private void JT_PeliculaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JT_PeliculaKeyPressed

    }//GEN-LAST:event_JT_PeliculaKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField JT_Genero;
    public static javax.swing.JTextField JT_Pelicula;
    public static javax.swing.JTextField JT_Sinopsis;
    public static javax.swing.JTextField JT_Tipo;
    private javax.swing.JButton btnAñadir;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabelPuest;
    private javax.swing.JLabel jLabelSuel;
    private javax.swing.JLabel jLabelSuel1;
    private javax.swing.JLabel jLabelSuel2;
    // End of variables declaration//GEN-END:variables
}
