/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package necflis;

/**
 *
 * @author Edman
 */
public class Peliculas extends javax.swing.JInternalFrame {

    /**
     * Creates new form Peliculas
     */
    public Peliculas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktop = new javax.swing.JDesktopPane();
        Ver_Peliculas = new javax.swing.JButton();
        Nue_Pelicula = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Películas");

        Ver_Peliculas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/necflis/peli.png"))); // NOI18N
        Ver_Peliculas.setText("Ver Listado de Películas");
        Ver_Peliculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ver_PeliculasActionPerformed(evt);
            }
        });

        Nue_Pelicula.setIcon(new javax.swing.ImageIcon(getClass().getResource("/necflis/mas pelicula.jpg"))); // NOI18N
        Nue_Pelicula.setText("Crear Nueva Películas");
        Nue_Pelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nue_PeliculaActionPerformed(evt);
            }
        });

        jDesktop.setLayer(Ver_Peliculas, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktop.setLayer(Nue_Pelicula, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopLayout = new javax.swing.GroupLayout(jDesktop);
        jDesktop.setLayout(jDesktopLayout);
        jDesktopLayout.setHorizontalGroup(
            jDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopLayout.createSequentialGroup()
                .addContainerGap(286, Short.MAX_VALUE)
                .addGroup(jDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Ver_Peliculas, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                    .addComponent(Nue_Pelicula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(286, Short.MAX_VALUE))
        );
        jDesktopLayout.setVerticalGroup(
            jDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopLayout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(Ver_Peliculas, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(Nue_Pelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(192, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktop)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Ver_PeliculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ver_PeliculasActionPerformed
        necflis.ListadoPeliculas lp = new necflis.ListadoPeliculas();
        jDesktop.add(lp);
        lp.show();
    }//GEN-LAST:event_Ver_PeliculasActionPerformed

    private void Nue_PeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nue_PeliculaActionPerformed
        necflis.NuevaPelicula np = new necflis.NuevaPelicula();
        jDesktop.add(np);
        np.show();
    }//GEN-LAST:event_Nue_PeliculaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Nue_Pelicula;
    private javax.swing.JButton Ver_Peliculas;
    private javax.swing.JDesktopPane jDesktop;
    // End of variables declaration//GEN-END:variables
}
