/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package necflis;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Edman
 */
public class SeleccionarCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form SeleccionarCliente
     */
    public SeleccionarCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jDesktop = new javax.swing.JDesktopPane();
        Clic_Clientes = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla1 = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Seleccionar Cliente");
        setVisible(false);

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));

        jDesktop.setBackground(new java.awt.Color(255, 255, 255));

        Clic_Clientes.setText("Clic para mostrar clientes");
        Clic_Clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Clic_ClientesActionPerformed(evt);
            }
        });

        Tabla1 = new JTable()
        {
            public boolean isCellEditable(int row, int column){
                for (int i = 0; i < Tabla1.getRowCount(); i++){
                    if(row == i){
                        return false;
                    }
                }
                return true;
            }
        };
        Tabla1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Dirección", "Edad", "PlayList"
            }
        ));
        Tabla1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tabla1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabla1);

        jDesktop.setLayer(Clic_Clientes, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktop.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopLayout = new javax.swing.GroupLayout(jDesktop);
        jDesktop.setLayout(jDesktopLayout);
        jDesktopLayout.setHorizontalGroup(
            jDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopLayout.createSequentialGroup()
                .addGap(352, 352, 352)
                .addComponent(Clic_Clientes)
                .addContainerGap(401, Short.MAX_VALUE))
            .addGroup(jDesktopLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jDesktopLayout.setVerticalGroup(
            jDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(Clic_Clientes, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        jDesktopPane1.setLayer(jDesktop, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addComponent(jDesktop)
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktop)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Clic_ClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Clic_ClientesActionPerformed
        String filePath = "clientes.txt";
        File file = new File(filePath);
        
        try {
            FileReader fr = new FileReader(file);
            BufferedReader br = new BufferedReader(fr);
            
            DefaultTableModel model = (DefaultTableModel)Tabla1.getModel();
            Object [] lines = br.lines().toArray();
            
            for(int i = 0; i < lines.length; i++){
                String[] row = lines[i].toString().split("-");
                model.addRow(row);
            }
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ListadoClientes.class.getName()).log(Level.SEVERE, null, ex);
        }
        Clic_Clientes.setEnabled(false);
    }//GEN-LAST:event_Clic_ClientesActionPerformed

    private void Tabla1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabla1MouseClicked

        if(evt.getClickCount() == 1){
            //JOptionPane.showMessageDialog(rootPane, "FILA: " + Tabla1.getSelectedColumn())
            necflis.Info in = new necflis.Info();
            jDesktop.add(in);
            in.show();

            String nombre=String.valueOf(Tabla1.getValueAt(Tabla1.getSelectedRow(),0));

            try{
            FileWriter Writer = new FileWriter("SeleccionarCliente.txt", true);
            Writer.write(nombre);
            Writer.write(System.getProperty("line.separator"));
            Writer.close();
            setVisible(true);
            new NuevoCliente().setVisible(true);
            }
            
            catch (Exception e){
                JOptionPane.showMessageDialog(null,"Error");
            }
        }
    }//GEN-LAST:event_Tabla1MouseClicked
        
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Clic_Clientes;
    private javax.swing.JTable Tabla1;
    private javax.swing.JDesktopPane jDesktop;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
